// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDV5E9DW1rPmwfl4nfIDDg5yRZZEHThBs',
    appId: '1:810760498631:web:c78bb9799655bb2c3cbde2',
    messagingSenderId: '810760498631',
    projectId: 'appointment-booking-57015',
    authDomain: 'appointment-booking-57015.firebaseapp.com',
    storageBucket: 'appointment-booking-57015.firebasestorage.app',
    measurementId: 'G-NEWXNBXPNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzhPVnK6GMpregB7jrybehoGEPp6vCfWk',
    appId: '1:810760498631:android:24f30ca267e76a8c3cbde2',
    messagingSenderId: '810760498631',
    projectId: 'appointment-booking-57015',
    storageBucket: 'appointment-booking-57015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQYxZcngQfCPgNXZfrtj7S30jUme893M',
    appId: '1:810760498631:ios:e543d2de6f357be93cbde2',
    messagingSenderId: '810760498631',
    projectId: 'appointment-booking-57015',
    storageBucket: 'appointment-booking-57015.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQYxZcngQfCPgNXZfrtj7S30jUme893M',
    appId: '1:810760498631:ios:e543d2de6f357be93cbde2',
    messagingSenderId: '810760498631',
    projectId: 'appointment-booking-57015',
    storageBucket: 'appointment-booking-57015.firebasestorage.app',
    iosBundleId: 'com.example.appointmentBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDV5E9DW1rPmwfl4nfIDDg5yRZZEHThBs',
    appId: '1:810760498631:web:c287a56cc47263ff3cbde2',
    messagingSenderId: '810760498631',
    projectId: 'appointment-booking-57015',
    authDomain: 'appointment-booking-57015.firebaseapp.com',
    storageBucket: 'appointment-booking-57015.firebasestorage.app',
    measurementId: 'G-W082TJWHP6',
  );
}
